name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: pytest tests/ --disable-warnings

    - name: Merge to main if successful
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo;
          const pullRequest = context.payload.pull_request;

          if (!pullRequest) {
            throw new Error("No pull request found in the context.");
          }

          const pull_number = pullRequest.number;

          if (!github.pulls || typeof github.pulls.merge !== "function") {
            throw new Error("GitHub API client is not properly initialized or lacks the required method.");
          }

          await github.pulls.merge({
            owner,
            repo,
            pull_number,
            merge_method: "squash"
          });


