name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: pytest tests/ --disable-warnings

    - name: Check if PR exists
      id: check_pr
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pullRequests } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:develop`,
            base: 'main'
          });

          if (pullRequests.length > 0) {
            console.log(`PR already exists: #${pullRequests[0].number}`);
            core.setOutput("pr_number", pullRequests[0].number);
          } else {
            console.log("No PR exists.");
            core.setOutput("pr_number", "");
          }

    - name: Create PR if not exists
      if: success() && steps.check_pr.outputs.pr_number == ''
      id: create_pr
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pullRequest } = await github.rest.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: 'develop',
            base: 'main',
            title: 'Merge develop into main',
            body: 'Tests passed, merging develop into main automatically.'
          });
          console.log(`Created PR #${pullRequest.number}`);
          core.setOutput("pr_number", pullRequest.number);

    - name: Merge PR
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          const prNumber = steps.create_pr.outputs.pr_number || steps.check_pr.outputs.pr_number;

          if (!prNumber) {
            throw new Error("No PR to merge");
          }

          await github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: prNumber
          });

          console.log(`Merged PR #${prNumber}`);
