name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: pytest tests/ --disable-warnings

    - name: Create and merge pull request
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;

          // Vérifiez si une pull request existe déjà de develop -> main
          const pulls = await github.rest.pulls.list({
            owner,
            repo,
            state: "open",
            head: `develop`,
            base: "main",
          });

          if (pulls.data.length === 0) {
            console.log("Aucune pull request existante, création en cours...");
            const pullRequest = await github.rest.pulls.create({
              owner,
              repo,
              head: "develop",
              base: "main",
              title: "Merge develop into main",
              body: "Cette pull request fusionne automatiquement develop dans main après tests réussis.",
            });

            console.log(`Pull request créée : #${pullRequest.data.number}`);
          } else {
            console.log("Une pull request existante a été trouvée.");
          }

          // Récupérez le numéro de la pull request
          const pullRequestNumber = (
            pulls.data.length > 0
              ? pulls.data[0].number
              : (await github.rest.pulls.create({
                  owner,
                  repo,
                  head: "develop",
                  base: "main",
                  title: "Merge develop into main",
                })).data.number
          );

          console.log(`Fusion de la pull request : #${pullRequestNumber}`);
          await github.rest.pulls.merge({
            owner,
            repo,
            pull_number: pullRequestNumber,
            merge_method: "squash",
          });
          console.log("Fusion réussie !");

